sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

install:
  - docker build --tag=wildfly-tests docker

before_script:
  - docker run -it -d  -p 8080:8080 -p 9990:9990 --name wildfly-tests wildfly-tests

script:
  - mvn clean test -Parq-wildfly-remote

notifications:
  email:
    - j.carmona.n@gmail.com
